
[profile.default]
evm_version = "cancun"
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 1000000
via_ir = true

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
     "erc721a/=node_modules/erc721a/",
    "@uniswap/=node_modules/@uniswap/",
    "@chainlink/=node_modules/@chainlink/",
    "forge-std/=lib/forge-std/src/"
]
